export const products = [
  {
    _id: '636985e59540445b3c45e6af',
    name: 'iPhone 11 Pro 256GB Memory',
    image: 'https://www.cricketwireless.com/uiassets/DAPW4943-list.png',
    description:
      'Shoot 4K video, beautiful portraits and sweeping landscapes with the all-new dual-camera system. Capture your best low-light photos with Night mode. See true-to-life colour in your photos, videos and games on the 6.1-inch Liquid Retina display.3 Experience unprecedented performance with A13 Bionic for gaming, augmented reality and photography',
    brand: 'Apple',
    category: 'Electronics',
    price: 929.99,
    rating: 3,
    numReviews: 1,
    isNew: false,

    reviews: [],
    stock: 5,
  },
  {
    _id: '6369860d9540445b3c45e6b1',
    name: 'Samsung Galaxy A13 5G',
    image: 'https://www.cricketwireless.com/uiassets/DSMW4138-list.png',
    description:
      "Samsung Galaxy A13 5G features a 6.5 inches PLS TFT display that has a 720 x 1600 pixels resolution. The device comes in a single color: Black. The smartphone is built with a Glass front, plastic back, and plastic frame.",
    brand: 'Samsung',
    category: 'Electronics',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 0,
    isNew: false,

    reviews: [],
    stock: 0,
  },
  {
    _id: '6369863c9540445b3c45e6b3',
    name: 'Motorola Moto g stylus 5G',
    image: 'https://www.cricketwireless.com/uiassets/DMTW4108-list.png',
    description:
      'Meet moto g stylus 5G – the best camera quality phone with a built-in stylus, a gorgeous ultra-wide display, and a versatile 50 MP camera system.',
    brand: 'Motorola',
    category: 'Electronics',
    price: 299.99,
    rating: 5,
    numReviews: 0,
    isNew: false,

    reviews: [],
    stock: 7,
  },
  {
    _id: '636986749540445b3c45e6b7',
    name: 'iPhone 13 512GB Memory',
    image: 'https://www.cricketwireless.com/uiassets/DAPW4260-list.png',
    description:
      'Product Product name Apple iPhone 13 mini 512GB Blue Product type Smartphone Display Display size 13.7 cm (5.4") Physical resolution 2340 x 1080 Touchscreen Multi-touch Design Colour Blue Processor Processor model A15 Bionic chip 64-bit Memory Internal memory 512 GB Memory card slot - Connectivity SIM card slot Dual SIM SIM card type Nano-SIM, eSIM Connectors 1 x Lightning Wireless Bluetooth, NFC, WLAN, WWAN Mobile network standard 5G, 2.75G / EDGE, 2G / GSM, 3.9G / LTE, 4G / LTE Advanced, 4.5G / LTE Advanced Pro, 3G / UMTS Camera Rear camera 12 MP + 12 MP Front camera 12 MP Physical properties Weight 0.140 Optional[kg] Dimensions (W x H x D) 64 x 132 x 8 Optional[mm] Operating system Operating system Apple iOS Performance Battery life (max.) 17 Optional[hours] Battery technology Li-ion Security Protection rating IP68 Security Facial recognition Special features Special features Dual-camera, True Tone display, Anti-smudge coating, Inductive charging Includes Includes USB Type-C - Lightning cable',
    brand: 'Apple',
    category: 'Electronics',
    price: 899.99,
    rating: 5,
    numReviews: 0,
    isNew: false,
    stock: 0,
  },
  {
    _id: '63804a5079636c2ced47757d',
    name: 'Apple Watch SE 40mm',
    image: 'https://tradelinestores.s3.amazonaws.com/media/product_images/e2100723-93b0-4693-b0d9-ee6c93ade9db.png  ',
    brand: 'Apple',
    category: 'Electronics',
    description:
      'Essential features to help you stay connected, active, healthy and safe. Perfect for kids and older adults using Family Setup',
    rating: 0,
    numReviews: 0,
    price: 699.99,
    stock: 5,
    isNew: true,
    reviews: [],
  },
  {
    _id: '6381275e8e8648e00b7c82f7',
    name: 'Shure MV7',
    image: 'https://products.shureweb.eu/cdn-cgi/image/width=1400,height=1400,format=auto/shure_product_db/product_images/files/e43/573/55-/header_transparent/72cf0784ef94b1e08c120ea10ab0ab7c.png',
    brand: 'Shure',
    category: 'Microphones',
    description:
      'Get a professional podcast sound with audio interfaces, hard disk recorders, or direct to computers and mobile devices with the Shure MV7 Podcasting Microphone (Black). This is a professional-quality, broadcast-style dynamic microphone, one that can has both a conventional XLR connection and a USB port. It also supports a 3.5mm headphone output for direct monitoring.',
    rating: 0,
    numReviews: 0,
    price: 449,
    stock: 2,
    isNew: true,
    reviews: [],
  },
];
